### ISSUE TITLE
Increase some clearances

### ISSUE THREAD

**Issue by up201605618** [SEAI-H-2020/Hardware-Documentation#112]
- [x] Power switch (SW1) to the board edge
- [x] Tracks to the H4 pad
- [x] Improve track clearances around component pins

(WIP in branch [simao](https://github.com/SEAI-H-2020/Hardware-Documentation/tree/simao), see #113 )

**Comment by up201605618** [comment]
@ruca03 feedback please:

![image](https://user-images.githubusercontent.com/47529104/104027340-2bc70a00-51bf-11eb-8436-b59fc1f326b1.png)
![image](https://user-images.githubusercontent.com/47529104/104027431-49946f00-51bf-11eb-8344-04b1bfb1e555.png)
![image](https://user-images.githubusercontent.com/47529104/104027461-55803100-51bf-11eb-9b9f-2620a1edb2c5.png)
![image](https://user-images.githubusercontent.com/47529104/104027474-5add7b80-51bf-11eb-996d-d22fae75c230.png)

**Comment by ruca03** [comment]
Tá top
